name: PR

on:
  push:
    paths:
      - '*.kicad_sch'
      - '*.kicad_pcb'
      - '.github/workflows/*yaml'
  pull_request:
    paths:
      - '*.kicad_sch'
      - '*.kicad_pcb'
      - '.github/workflows/*yaml'
  repository_dispatch:
    types: [run_qs]

jobs:
  KiBot-Generation:
    runs-on: ubuntu-latest  # Don't change
    container: ghcr.io/inti-cmnb/kicad8_auto_full:latest

    steps:
    - name: Checkout repo
      uses: actions/checkout@v4
      with:
        # So we can run a diff between last 2 changes
        fetch-depth: '0'

    - name: Quick Start
      run: |
        kibot --quick-start

    - name: Retrieve results
      uses: actions/upload-artifact@v4
      with:
        name: Automatic_outputs
        path: Generated
